### ISSUE TITLE
it would be great if you put multiple azure accounts

### ISSUE THREAD

**Issue by gersonbzr86** [dan-gut1/azure-controller-bot#9]
it would be great if you put multiple azure accounts

**Comment by dan-gut1** [comment]
OK I've design dilema.
Would you like to instantiate azure wrapper with the vm inside it and operate it as simple as followed.

Example 1
```db_vm_eastus = azurelib("db_vm") 
ngix_vm_eastus = azurelib("ngix_vm")
dm_vm_eastus.start_vm()
ngix_vm_eastus.start_vm()
```
Or instantiate azure functionality and provide the vm that should the operation that should be on, in every call? 
Example 2

```azure_eastus= azurelib() 
azure_germany= azurelib() 
azure_eastus.start_vm("db_vm")
azure_germany.start_vm("ngix_vm")
```

**Comment by dan-gut1** [comment]
@gersonbzr86 
i've the azurelib to support multiple azure accounts, you can now instantiate the lib like below.

```
db_vm_eastus = azurelib("db_vm") 
ngix_vm_eastus = azurelib("ngix_vm")
db_vm_eastus.start_vm()
ngix_vm_eastus.start_vm()
```

of curse you need to rename and modify azure_credential_param_example.json and manifest you azure VM's.

**Comment by dan-gut1** [comment]
I can make it more generic if you need to...

**Comment by gersonbzr86** [comment]
what I would like is support for multiple microsoft/azure accounts and for several vms, because I have many accounts on azure with 4 vms in each

can you do an update for this?

**Comment by gersonbzr86** [comment]
Yes, I need it, because I'm a layman

**Comment by dan-gut1** [comment]
> what I would like is support for multiple microsoft/azure accounts and for several vms, because I have many accounts on azure with 4 vms in each
> 
> can you do an update for this?

The why I currently implemented it not  ideal for you but you still can use it on multi VM's per azure account if you edit `azure_credential_param.json`
as follow
```
{
    "vm_name1":{
        "location": "Datacenter location",
        "group_name": "Resource group name the vm seats in",
        "subscription_id": "subscription_id goes here",
        "tenant_id": "tenant_id goes here",
        "client_id": "client_id goes here",
        "client_secret": "client_secret goes here"
    },
   "vm_name2":{
        "location": "Datacenter location",
        "group_name": "Resource group name the vm seats in",
        "subscription_id": "subscription_id goes here",
        "tenant_id": "tenant_id goes here",
        "client_id": "client_id goes here",
        "client_secret": "client_secret goes here"
    },
   "vm_name3":{
        "location": "Datacenter location",
        "group_name": "Resource group name the vm seats in",
        "subscription_id": "subscription_id goes here",
        "tenant_id": "tenant_id goes here",
        "client_id": "client_id goes here",
        "client_secret": "client_secret goes here"
    }
}
```

and initiate the object as follow
```

vm_1 = azurehandler("vm_name1")
vm_2 = azurehandler("vm_name2")
vm_3 = azurehandler("vm_name3")
```

I will add setter soon but it will required  structure change of `azure_credential_param.json`

**Comment by gersonbzr86** [comment]
ok, thank you

**Comment by gersonbzr86** [comment]
C:\Users\Luci\Pictures\azure-controller-bot-master\azure-controller-bot-master>main.py
init telegrambot
No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\Luci\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\ext\dispatcher.py", line 557, in process_update
    handler.handle_update(update, self, check, context)
  File "C:\Users\Luci\AppData\Local\Programs\Python\Python310\lib\site-packages\telegram\ext\handler.py", line 199, in handle_update
    return self.callback(update, context)
  File "C:\Users\Luci\Pictures\azure-controller-bot-master\azure-controller-bot-master\main.py", line 35, in vm_start
    with AzureHandler() as vm:
TypeError: AzureHandler.__init__() missing 1 required positional argument: 'vm_name'

**Comment by gersonbzr86** [comment]
I have a little problem to configure could you help me via anydesk or telegram?

**Comment by dan-gut1** [comment]
yes how do I PM you on github my telegram

**Comment by gersonbzr86** [comment]
@rafaelatks my telegram

**Comment by dan-gut1** [comment]
#12 and Commit 8b44850 I commit to master by mistake,should cover all your needs.
